'use client';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import Queue from './queue';import RevisedQueue from './queue-revision';import {Header} from './shared';import './prototype.css';import './revision.css';import './picker.css';
const names=['Original','Inline proof','Evidence rail','Claim ledger'];
const variants=[Queue,()=> <RevisedQueue reviewMode="inline"/>,()=> <RevisedQueue reviewMode="rail"/>,()=> <RevisedQueue reviewMode="ledger"/>];
export default function Prototype({initialVariant}:{initialVariant:number}){const [current,setCurrent]=useState(initialVariant);const [replay,setReplay]=useState(0);const picker=useRef<HTMLElement>(null);
useEffect(()=>{requestAnimationFrame(()=>requestAnimationFrame(()=>picker.current?.setAttribute('data-ready','')))},[]);
useLayoutEffect(()=>{function move(){const nav=picker.current!;const item=nav.querySelectorAll<HTMLButtonElement>('.proto-picker-item')[current];const highlight=nav.querySelector<HTMLElement>('.proto-picker-highlight')!;highlight.style.width=item.offsetWidth+'px';highlight.style.transform=`translateX(${item.offsetLeft}px)`}move();window.addEventListener('resize',move);return()=>window.removeEventListener('resize',move)},[current]);
function select(n:number){setCurrent(n);setReplay(x=>x+1);const url=new URL(location.href);url.searchParams.set('v',String(n+1));history.replaceState(null,'',url)}
useEffect(()=>{function key(e:KeyboardEvent){const el=e.target as HTMLElement;if(/^(INPUT|TEXTAREA|SELECT)$/.test(el.tagName)||el.isContentEditable||e.metaKey||e.ctrlKey||e.altKey||document.querySelector('[role="dialog"]'))return;const n=parseInt(e.key,10);if(n>=1&&n<=4)select(n-1);else if(e.key==='ArrowRight'){e.preventDefault();select((current+1)%4)}else if(e.key==='ArrowLeft'){e.preventDefault();select((current+3)%4)}else if(e.key.toLowerCase()==='r')setReplay(x=>x+1)}document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[current]);const Variant=variants[current];return <div className="underwriting-prototype"><Header compact={current>0}/><Variant key={`${current}-${replay}`}/><nav ref={picker} className="proto-picker" aria-label="Prototype variants"><span className="proto-picker-highlight" aria-hidden="true"/>{names.map((n,i)=><button key={n} className="proto-picker-item" data-active={i===current?'':undefined} aria-current={i===current?'true':undefined} onClick={()=>select(i)}>{n}</button>)}</nav></div>}
