'use client';
import { useState } from 'react';
import { Dialog } from '@base-ui/react/dialog';
import { Account, accounts, groups } from './data';
export function Badge({a}:{a:Account}) {return <span className={`badge ${a.group==='Investigate'?'amber':a.group==='Out of appetite'?'red':a.status==='Target'?'green':a.status==='Acceptable'?'acceptable':''}`}>{a.status}</span>}
export function Filters({value,onChange}:{value:string;onChange:(v:string)=>void}) {return <div className="filters" aria-label="Action groups">{groups.map(g=><button key={g} aria-pressed={value===g} onClick={()=>onChange(g)}>{g}<span>{accounts.filter(a=>a.group===g).length}</span></button>)}</div>}
export function Facts({a}:{a:Account}) {return <div className="facts">{[['Risk state',a.state],['Insured value',`$${a.tiv}M`],['Premium',`$${a.premium}K`],['Built',a.year]].map(([k,v])=><div key={k}><small>{k}</small><strong>{v}</strong></div>)}</div>}
export function Detail({a}:{a:Account}) {
 const [tab,setTab]=useState('Assessment'); const [action,setAction]=useState(false);
 return <div className="detail"><div className="eyebrow">SUBMISSION {a.id} · NEW BUSINESS</div><h2>{a.name}</h2><p className="muted">Commercial property · 1 location · USD</p><Badge a={a}/><Facts a={a}/><div className="detail-tabs">{['Assessment','Sources','Agent activity'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='Assessment'&&<><h3>{a.group==='Pursue'?'Why this belongs in pursuit':a.group==='Investigate'?'One gap to resolve':'Confirmed exclusion'}</h3><p>{a.reason}</p><div className="assessment-note">{a.group==='Pursue'?`${a.targets.filter(Boolean).length} of 4 target preferences · ${a.targets.filter(Boolean).length*25}/100 fit`:a.group==='Investigate'?'Potential target fit · no final score until eligible':'Not scored · an exclusion cannot be offset by target matches'}</div><h3>Target preferences</h3>{['Risk state','Total insured value','Premium','Building age'].map((x,i)=><div className="criterion" key={x}><span>{x}</span><span>{a.targets[i]?'Target · 25':a.id==='D'&&i===2?'Outside appetite':'Acceptable · 0'}</span></div>)}<p className="caption">Equal weights are a team policy (rubric v0.1), not a probability or profit forecast.</p><h3>Eligibility checks</h3>{['New Property business','Construction: 100% noncombustible',a.id==='E'?'Five-year losses: unknown':'Five-year losses: complete · $40,000'].map((s,i)=><div className="criterion" key={s}><span>{s}</span><span>{a.id==='E'&&i===2?'Unknown':'Pass'}</span></div>)}<p className="caption">Illustrative cases: one building; losses use a fixed five-year fixture window ending Sep 19, 2026.</p></>}
 {tab==='Sources'&&<><h3>Evidence behind the recommendation</h3><p className="caption">Fictional fixture records, adapted from the rubric’s A–E cases. These are not live API results.</p>{[['Risk state',a.state,`Location LOC-${a.id} · state`],['Insured value',`$${a.tiv}M`,`Building BLD-${a.id} · tiv`],['Premium',`$${a.premium}K`,`Policy POL-${a.id} · premium`],['Building year',String(a.year),`Building BLD-${a.id} · year_built`],['Loss history',a.id==='E'?'Unavailable':'Complete · $40,000',a.id==='E'?'No completeness evidence':'Fixture loss summary · 2021–2026']].map(([k,v,s])=><div className="source" key={k}><strong>{k}<span>{v}</span></strong><code>{s}</code></div>)}</>}
 {tab==='Agent activity'&&<><h3>How the evidence was gathered</h3><p className="caption">Illustrative action summaries. No model or API has run.</p>{['Discover available resources and field types','Find policies linked to submission '+a.id,'Follow exposure references to the building',a.id==='E'?'Loss-history coverage unresolved; keep in investigation':'Verify five-year loss coverage and evaluate rules'].map((s,i)=><div className="activity" key={s}><span>{i+1}</span><p>{s}</p></div>)}<details><summary>Show illustrative query intent</summary><pre>{JSON.stringify({resource:'Policy',relation:'submission',submission_id:a.id,purpose:'Retrieve premium and linked exposure evidence'},null,2)}</pre></details></>}
 <div className="detail-action"><button className="primary" onClick={()=>setAction(true)}>{action?(a.id==='E'?'Request draft prepared':'Review opened in prototype'):a.action} <span>↗</span></button>{action&&<div role="status" className="action-result">{a.id==='E'?<><strong>Draft request · not sent</strong><p>Please provide complete five-year loss runs for Northline Logistics, including confirmation of years with no claims.</p></>:<><strong>Review checklist</strong><p>Confirm source evidence and document your underwriting decision. This prototype does not approve or decline coverage.</p><label>Review notes<textarea placeholder="Add your assessment…"/></label></>}</div>}</div></div>
}
export function AccountDialog({a,label}:{a:Account;label?:string}) {return <Dialog.Root><Dialog.Trigger className="text-button">{label||'Review'} <span>↗</span></Dialog.Trigger><Dialog.Portal><Dialog.Backdrop className="proto-backdrop"/><Dialog.Popup className="proto-drawer"><Dialog.Title className="sr-only">Review {a.name}</Dialog.Title><Dialog.Close className="close" aria-label="Close review">×</Dialog.Close><Detail a={a}/></Dialog.Popup></Dialog.Portal></Dialog.Root>}
export function Rules(){return <Dialog.Root><Dialog.Trigger className="rule-button">Property appetite <span>v0.1 ↗</span></Dialog.Trigger><Dialog.Portal><Dialog.Backdrop className="proto-backdrop"/><Dialog.Popup className="proto-drawer"><Dialog.Close className="close" aria-label="Close rules">×</Dialog.Close><Dialog.Title className="rule-title">How the queue is prioritized</Dialog.Title><Dialog.Description>Carrier appetite determines eligibility. Team preferences order eligible accounts.</Dialog.Description><h3>1. Check eligibility</h3><p>New Property business, acceptable state, positive insured value up to $150M, premium $50K–$175K, buildings newer than 1990, acceptable construction, and complete five-year losses under $100K.</p><h3>2. Separate unknowns</h3><p>Missing or ambiguous evidence stays in Investigate. A confirmed exclusion stays Out of appetite.</p><h3>3. Count target preferences</h3><p>25 points each: target state (OH, PA, MD, CO, CA, FL), $50M–$100M insured value, $75K–$100K premium, and building year after 2010.</p><p>Four matches means Target. Other eligible cases are Acceptable. Equal scores use received date, then ID, for display order only.</p><div className="assessment-note">Proposed team rubric v0.1. Scores do not predict approval, losses, or profitability. Boundary ambiguities require review.</div></Dialog.Popup></Dialog.Portal></Dialog.Root>}
export function Header({compact=false}:{compact?:boolean}){return <header className={`topbar${compact?' topbar-compact':''}`}><div className="brand"><span className="brand-mark">u</span>underwrite{!compact&&<><span className="brand-divider"/>Submission review</>}</div><div className="header-right"><span className="demo">Fictional demo</span><span className="avatar">JD</span></div></header>}
