import { ArrowRight, CheckCircle2, CircleAlert, FileText, MapPin, MessageSquareText, ShieldCheck, Sparkles } from "lucide-react";
import type { Submission, UnderwritingFinding } from "../lib/contracts";
import { StatusBadge } from "./StatusBadge";

export function UnderwritingWorkspace({ submission, findings, running, onRun }: { submission: Submission; findings: UnderwritingFinding[]; running: boolean; onRun: () => void }) {
  return <main className="workspace" aria-label="Submission review">
    <section className="case-header"><div className="case-breadcrumb"><span>Commercial property</span><ArrowRight size={13} /><span>{submission.id}</span></div><div className="case-title-row"><div><h1>{submission.insured}</h1><p><MapPin size={14} />{submission.location} · {submission.line}</p></div><div className="case-actions"><button className="secondary-button"><FileText size={16} />View documents</button><button className="primary-button" onClick={onRun} disabled={running}>{running ? <><Sparkles size={16} className="spin" />Running</> : <><Sparkles size={16} />Run analysis</>}</button></div></div><div className="case-summary"><div><span>Premium</span><strong>${submission.premium.toLocaleString()}</strong></div><div><span>Total insured value</span><strong>${(submission.tiv / 1000000).toFixed(1)}m</strong></div><div><span>Risk score</span><strong>{submission.riskScore}<small>/100</small></strong></div><div className="appetite-summary"><span>Appetite result</span><StatusBadge tone={submission.statusTone} label={submission.appetite} /></div></div></section>
    <section className="conversation" aria-labelledby="conversation-heading"><div className="section-heading"><div><p className="eyebrow">Agent review</p><h2 id="conversation-heading">Underwriting analysis</h2></div><span className="model-note"><Sparkles size={14} />Evidence linked</span></div>
      <div className="conversation-stream"><article className="agent-message"><div className="agent-avatar"><ShieldCheck size={17} /></div><div><div className="message-meta"><strong>Underwriting agent</strong><span>10:42 AM</span></div><p>I reviewed the submitted ACORD package, enriched the Fresno property, checked five-year loss signals, and applied the Commercial Property appetite guidelines.</p></div></article>
        <article className="agent-message"><div className="agent-avatar muted"><MessageSquareText size={17} /></div><div><div className="message-meta"><strong>Decision rationale</strong><span>Confidence 86%</span></div><p>The account is broadly eligible but should be referred because the wildfire proximity and two water losses trigger guideline thresholds <button className="inline-link">WF-17</button> and <button className="inline-link">LH-04</button>.</p></div></article></div>
      <article className="recommendation"><div className="recommendation-top"><div><p className="eyebrow">Recommended disposition</p><h3>Refer with conditions</h3></div><StatusBadge tone="warning" label="Human review required" /></div><p className="recommendation-copy">Proceed to underwriting review after confirming the roof inspection and applying the wildfire deductible. No automatic decline criteria were found.</p><div className="recommendation-actions"><button className="secondary-button">Request information</button><button className="primary-button"><CheckCircle2 size={16} />Approve referral</button></div></article>
    </section>
      <section className="findings"><div className="section-heading compact"><div><p className="eyebrow">Evidence first</p><h2>Risk drivers</h2></div><button className="quiet-button">View all evidence <ArrowRight size={14} /></button></div><div className="finding-grid">{findings.map((finding) => <article className="finding" key={finding.label}><div className={`finding-icon ${finding.tone}`}>{finding.tone === "success" ? <CheckCircle2 size={16} /> : <CircleAlert size={16} />}</div><div><strong>{finding.label}</strong><p>{finding.detail}</p></div></article>)}</div></section>
  </main>;
}
