from __future__ import annotations

from datetime import date

from .models import BuildingEvidence, ClaimEvidence, SubmissionEvidence


def _building(
    identifier: str,
    year: int | None,
    construction: str | None,
    tiv: float | None,
    *,
    occupancy: str | None = None,
    sprinklered: bool | None = None,
    protection_class: str | None = None,
    flood_zone: str | None = None,
    wildfire_score: float | None = None,
) -> BuildingEvidence:
    return BuildingEvidence(
        id=identifier,
        year_built=year,
        construction_type=construction,
        tiv=tiv,
        occupancy=occupancy,
        sprinklered=sprinklered,
        protection_class=protection_class,
        flood_zone=flood_zone,
        wildfire_score=wildfire_score,
    )


def _claim(identifier: str, loss_date: date | None, value: float | None) -> ClaimEvidence:
    return ClaimEvidence(id=identifier, loss_date=loss_date, loss_value=value)


DEMO_SUBMISSIONS: list[SubmissionEvidence] = [
    SubmissionEvidence(
        id="101",
        submission_number="SUB-2026-0101",
        insured_name="Meridian Cold Storage",
        received_date=date(2026, 9, 18),
        effective_date=date(2026, 11, 1),
        expiration_date=date(2027, 11, 1),
        submission_type="new_business",
        line_of_business="property",
        primary_state="OH",
        tiv=78_000_000,
        premium=92_000,
        buildings=[
            _building(
                "B-101-A", 2016, "non-combustible steel", 48_000_000,
                occupancy="Cold storage warehouse", sprinklered=True,
                protection_class="3", flood_zone="X",
            ),
            _building(
                "B-101-B", 2018, "masonry non-combustible", 30_000_000,
                occupancy="Cold storage warehouse", sprinklered=True,
                protection_class="3", flood_zone="X",
            ),
        ],
        claims=[_claim("C-101-A", date(2024, 2, 14), 12_400)],
    ),
    SubmissionEvidence(
        id="102",
        submission_number="SUB-2026-0102",
        insured_name="Apex Precision Works",
        received_date=date(2026, 9, 17),
        effective_date=date(2026, 10, 15),
        expiration_date=date(2027, 10, 15),
        submission_type="new",
        line_of_business="commercial property",
        primary_state="PA",
        tiv=64_000_000,
        premium=82_500,
        buildings=[
            _building(
                "B-102-A", 2014, "joisted masonry", 64_000_000,
                occupancy="Precision manufacturing", sprinklered=True,
                protection_class="4", flood_zone="X",
            )
        ],
        claims=[],
    ),
    SubmissionEvidence(
        id="103",
        submission_number="SUB-2026-0103",
        insured_name="Cedar Ridge Foods",
        received_date=date(2026, 9, 16),
        effective_date=date(2026, 12, 1),
        expiration_date=date(2027, 12, 1),
        submission_type="new business",
        line_of_business="property",
        primary_state="NC",
        tiv=42_000_000,
        premium=63_000,
        buildings=[_building("B-103-A", 2008, "masonry non-combustible", 42_000_000)],
        claims=[_claim("C-103-A", date(2022, 4, 8), 22_000)],
    ),
    SubmissionEvidence(
        id="104",
        submission_number="SUB-2026-0104",
        insured_name="Great Basin Plastics",
        received_date=date(2026, 9, 14),
        effective_date=date(2026, 11, 15),
        expiration_date=date(2027, 11, 15),
        submission_type="new_business",
        line_of_business="property",
        primary_state="UT",
        tiv=118_000_000,
        premium=155_000,
        buildings=[_building("B-104-A", 2001, "non-combustible", 118_000_000)],
        claims=[_claim("C-104-A", date(2023, 9, 20), 48_000)],
    ),
    SubmissionEvidence(
        id="105",
        submission_number="SUB-2026-0105",
        insured_name="Atlas Senior Living",
        received_date=date(2026, 9, 18),
        submission_type="new_business",
        line_of_business="property",
        primary_state="CA",
        tiv=156_000_000,
        premium=98_000,
        buildings=[_building("B-105-A", 2019, "non-combustible steel", 156_000_000)],
        claims=[],
    ),
    SubmissionEvidence(
        id="106",
        submission_number="SUB-2026-0106",
        insured_name="Harborview Hospitality",
        received_date=date(2026, 9, 13),
        submission_type="new_business",
        line_of_business="property",
        primary_state="FL",
        tiv=72_000_000,
        premium=42_000,
        buildings=[_building("B-106-A", 2015, "masonry non-combustible", 72_000_000)],
        claims=[],
    ),
    SubmissionEvidence(
        id="107",
        submission_number="SUB-2026-0107",
        insured_name="Keystone Retail Group",
        received_date=date(2026, 9, 12),
        submission_type="renewal",
        line_of_business="property",
        primary_state="MD",
        tiv=88_000_000,
        premium=94_000,
        buildings=[_building("B-107-A", 2017, "joisted masonry", 88_000_000)],
        claims=[],
    ),
    SubmissionEvidence(
        id="108",
        submission_number="SUB-2026-0108",
        insured_name="Bluebird Distribution",
        received_date=date(2026, 9, 11),
        submission_type="new_business",
        line_of_business="property",
        primary_state="VA",
        tiv=53_000_000,
        premium=79_000,
        buildings=[_building("B-108-A", None, "non-combustible steel", 53_000_000)],
        claims=[],
    ),
    SubmissionEvidence(
        id="109",
        submission_number="SUB-2026-0109",
        insured_name="Aspen Ridge Fabrication",
        received_date=date(2026, 9, 10),
        submission_type="new_business",
        line_of_business="property",
        primary_state="CO",
        tiv=96_000_000,
        premium=99_000,
        buildings=[_building("B-109-A", 1990, "masonry non-combustible", 96_000_000)],
        claims=[],
    ),
    SubmissionEvidence(
        id="110",
        submission_number="SUB-2026-0110",
        insured_name="Carolina Textile Cooperative",
        received_date=date(2026, 9, 9),
        submission_type="new_business",
        line_of_business="property",
        primary_state="SC",
        tiv=67_000_000,
        premium=88_000,
        buildings=[_building("B-110-A", 2006, "joisted masonry", 67_000_000)],
        claims=[_claim("C-110-A", None, 18_000)],
        conflicts=["Claim C-110-A has a loss value but no loss date."],
    ),
    SubmissionEvidence(
        id="111",
        submission_number="SUB-2026-0111",
        insured_name="Sonoran Packaging",
        received_date=date(2026, 9, 8),
        submission_type="new_business",
        line_of_business="property",
        primary_state="AZ",
        tiv=84_000_000,
        premium=90_000,
        buildings=[_building("B-111-A", 2012, "non-combustible steel", 84_000_000)],
        claims=[],
    ),
    SubmissionEvidence(
        id="112",
        submission_number="SUB-2026-0112",
        insured_name="Foundry Square Offices",
        received_date=date(2026, 9, 7),
        submission_type="new_business",
        line_of_business="property",
        primary_state="CO",
        tiv=132_000_000,
        premium=142_000,
        buildings=[_building("B-112-A", 2004, "masonry non-combustible", 132_000_000)],
        claims=[_claim("C-112-A", date(2025, 1, 3), 31_000)],
    ),
]
